#Problem: Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
#Solution: Create a Fibonacci function, generate each number up until four million, then sum up the even terms
def Fibo(x):
  if x==0:
    return 1
  if x==1:
    return 1
  else:
    return Fibo(x-1) + Fibo(x-2)
result = []
i=0
while (Fibo(i)<4000000):
  result.append(Fibo(i))
  i = i+1
x=0
for i in result:
  if i%2==0:
    x=x+i
print(x)

